version: "2.3"

services:
  jupyterlab:
    image: tensorflow-jupyterlab
    runtime: nvidia
    ipc: host
    ports:
      - "8888:8888"
    volumes:
      - /home/shlee/notebook:/notebook
      - /dataset:/dataset    